Migrate build logic to Kotlin DSL
gradle/common-custom-user-data-gradle-plugin pull request #298
Opened 2024-04-05 02:35 UTC by 3flex

Closes #186 

The diff below makes it hard to review, but the commit history should be clear.

2024-04-05 04:55 UTC, Goooler approved these changes

2024-04-05 04:55 UTC, Goooler commented on build.gradle.kts
> +    token(System.getenv("CCUD_GIT_TOKEN") ?: "")
```suggestion
    token(providers.environmentVariable("CCUD_GIT_TOKEN").orNull.orEmpty())
```

2024-04-08 14:12 UTC, clayburn requested changes
Thanks for the contribution @3flex! I made one suggestion. If you take that and fix the merge conflict, we'd be happy to accept this.

2024-04-08 14:12 UTC, clayburn commented on settings.gradle.kts
> +    id("com.gradle.common-custom-user-data-gradle-plugin") version "2"
```suggestion
    id("com.gradle.common-custom-user-data-gradle-plugin") version "2.0"
```

2024-04-08 23:14 UTC, 3flex commented
Fixed - I've also updated README in the last commit as there were a few references (and a link) to settings.gradle. Please check that before merging, thanks!

2024-04-09 00:57 UTC, clayburn approved these changes

2024-04-09 00:57 UTC, merged